---
title: "Considerations for Pursuing a Doctorate Degree in Biostatistics"
date: "December 2023"
---

I started the DrPH (Doctorate of Public Health) with a concentration in Biostatistics in the Fall of 2019 as a part-time student while working full time. I often meet with working biostatisticians or other professionals with MS or MPH degrees who are considering returning to school for their doctorate. They’ve gone beyond undergrad and know what graduate work entails and they have questions about getting back into school after working for a period of time, sometimes potentially balancing school while continuing to work. 

Everyone’s situation is completely different, so rather than offer guidance based on my own experience, I’ve compiled a few questions to guide the deeply personal decision about whether to return to school. When I went through this decision-making process, I didn’t know what I didn’t know, and hope to clarify some of that for anyone who is considering this decision. 

1.	What will you gain by going through the program? Is it a promotion from your current role? A different path altogether? Opportunity in another setting (e.g., a specific role in academia or in industry)? It can help to have a clear end goal in sight. 
    -	Are there other paths to that end goal other than going back to school? Do the years of experience that you will gain working in the time it would have taken to complete the program count for as much as the degree?
2.	What are the things that you can’t do without the degree? How much do you want to do those things?
3.	What are you willing to give up to be able to add this to your plate? Does this impact other life plans?
4.	What type of program are you considering, and how does that align with your goals? The most common doctorate degree in biostatistics is a traditional PhD, but there are alternatives, including the DrPH, which offers a more applied degree with emphasis on leadership in public health.
5.	Who will your support system be? An aside that I am a cohort of one in my program, and while this wasn’t a problem while I was going through coursework as there were other students I could chat with, it is a challenging place to be while dissertating. At work, I’m the only person who’s currently in school, and at school, I’m the only person who also works. This can feel isolating and forces me to be intentional about finding support. 
6.	I once read a book in which the author (comedian Chris Gethard) said before making a decision he asked himself, *Why this? Why here? Why now?*
7.	Does the program you are considering offer any financial support? Sometimes financial support is available but not advertised, so it is always worth an ask. 

If you are considering continuing to work while pursuing school:

8.	Will you work part-time or attend school part-time?
9.	(How) Does the program support students who work? When are classes scheduled? If they are scheduled during the day, will your workplace offer flexible hours so that you can attend classes?
    -	I have found two classes per semester to be the absolute maximum that is feasible, and they should be balanced in terms of workload and difficulty (don’t take two challenging classes in the same semester, you won’t get anything out of either of them). 
    -	Think about summer classes. Since two classes per semester means the pace of the program is pretty slow, adding some summer classes can help keep things moving. 
10.	If you will have financial support through tuition reimbursement, are there requirements tied to it, such as having to stay at your job for a certain period of time after completing the degree? Do you have to pay the money back if you ultimately decide not to complete the degree?

Pursuing a doctorate degree in (bio)statistics has been a much-discussed topic, and I hope that this blog post contributes to that discussion with an angle towards returning to school after a period of working and potentially while continuing to work full or part-time. Other articles about MS vs PhD career paths and career planning more broadly may be helpful:

* [To Get a PhD or Not to Get a PhD?](https://magazine.amstat.org/blog/2020/10/01/to-get-a-phd-or-not-to-get-a-phd/ )
* [What to Ask About Graduate School in Biostatistics](https://stattrak.amstat.org/2021/07/01/grad-school-in-biostatistics/)
* [Reflections on the Transition from Master’s to PhD Biostatistician](https://stattrak.amstat.org/2023/12/01/mastersphdbiostatistician/)
* [The Leek Group Guide to Career Planning](https://github.com/jtleek/careerplanning)
