---
title: "<br>"
output:  html_document
---
<link rel="stylesheet" href="fonts/academicons.min.css"/>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-137654852-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-137654852-1');
</script>

I am committed to working towards a more inclusive field for the next generation of biostatisticians. To that end, I have served in multiple roles as part of the Caucus for Women in Statistics and am a member of the Memorial Sloan Kettering [Bridge to Biostats](https://www.mskcc.org/departments/epidemiology-biostatistics/bridge-biostats) committee, which seeks to foster a more inclusive biostats community by creating programs to increase awareness of and interest in the field of Biostatistics among New York City public high school students. Related presentations, articles and memberships are highlighted below. 

* [Virtual Biostats Day: An Interactive Online Biostatistics Outreach Program Directed at High School Students in Groups Historically Underrepresented in STEM Careers](https://www.tandfonline.com/doi/full/10.1080/26939169.2024.2362150). Journal of Statistics and Data Science Education (2024)
* Mentored high school students (2021, 2024) for the [Bridge to Biostats Summer Exposure Program](https://www.mskcc.org/education-training/bridge-to-biostats-summer-program-b2bsp)
* Co-led 8th grade and high school “Biostats Days” to introduce students to biostatistics (December 2020, March 2021, April and July 2022, March, July and November 2023, May and June 2024). Partner organizations include [Bridge to Enter Advanced Mathematics](https://www.beammath.org/), [Baruch Step Academy](https://step.baruch.cuny.edu/), and [Success Academy](https://www.successacademies.org/).
  - Our program features a presentation by a Featured Biostatistician. Find out more information about volunteering to present on your path to biostatistics in our April 2023 [AmStat News article](https://magazine.amstat.org/blog/2023/04/01/biostats-exposure-program/).
* Organized a contributed panel discussion on [Skills & Strategies for Successful Negotiation](https://ww2.amstat.org/meetings/wsds/2020/onlineprogram/AbstractDetails.cfm?AbstractID=309555) at the Women in Statistics and Data Science Conference (2020) featuring panelists Dr. Emma Benn, Professor Lori Evarts, Dr. Shanthi Sethuraman, and Dr. Kelly Zou. A recap of the session was published in the February 2021 issue of [AmStat News](https://magazine.amstat.org/blog/2021/02/01/successful-negotiation).
* Presented on my path to a career in biostatistics to the Loyola University Maryland [CPaMS Scholars](https://www.loyola.edu/join-us/cpams-program) students (2022 and 2023)
* Presented in an 8th grade Bridge to Enter Advanced Mathematics Career Day (2020)
* Mentor in the New York Academy of Sciences' *1000 Girls, 1000 Futures* mentoring program (2018-2021). Published a corresponding [article](http://magazine.amstat.org/blog/2018/11/01/1000-girls-1000-futures/?utm_source=informz&utm_medium=email&utm_campaign=amstatnews&_zs=UvcOe1&_zl=vBfH5) highlighting this mentorship opportunity.   
*  [Caucus for Women in Statistics](https://cwstat.org/)
    * Social Media Officer (2020-2022)
    * Volunteer Coordinator (appointed position, 2019-2020)    
    * Professional Development Committee Member (2020-2021)
    * Promoting Positive Professional Environments for Everyone Committee Member (2020-2021)
    * Moderated the March 2020 Caucus for Women in Statistics Lunch & Learn on [Navigating social media and managing your professional presence online](https://cwstat.org/march-31st-lunch-learn-on-creating-a-professional-online-presence-view-recording/). Check out my [blog post](blog_cws_social_media_webinar.html) about this Lunch & Learn for more information. 
* Presented [Language and Tools for Establishing Influence as an Early-Career Statistician](https://ww2.amstat.org/meetings/wsds/2017/onlineprogram/AbstractDetails.cfm?AbstractID=303802) at the Women in Statistics and Data Science Conference (2017) and published a corresponding [article](http://magazine.amstat.org/blog/2018/05/01/earlycareertools/).  
*  Member of [RLadies NYC](http://www.rladiesnyc.org/)  