---
title: "Leadership and Volunteer Activities"
output:  html_document
---
<link rel="stylesheet" href="fonts/academicons.min.css"/>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-137654852-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-137654852-1');
</script>

## Women in STEM
* Presented [Language and Tools for Establishing Influence as an Early-Career Statistician](https://ww2.amstat.org/meetings/wsds/2017/onlineprogram/AbstractDetails.cfm?AbstractID=303802) at the 2017 Women in Statistics and Data Science Conference   
    - Corresponding AmStat News [article](http://magazine.amstat.org/blog/2018/05/01/earlycareertools/)  
* Mentor in the New York Academy of Sciences' 1000 girls, 1000 futures mentoring program (2018-2019)
    - Corresponding AmStat News [article](http://magazine.amstat.org/blog/2018/11/01/1000-girls-1000-futures/?utm_source=informz&utm_medium=email&utm_campaign=amstatnews&_zs=UvcOe1&_zl=vBfH5)  
*  Member of [RLadies NYC](http://www.rladiesnyc.org/)  
*  [Caucus for Women in Statistics](https://cwstat.org/)
    * Volunteer Coordinator 2019-2020)    
    * Professional Development Committee Member (2020-)
    * Promoting Positive Professional Environments (P3) Ad Hoc Committee Member (2020-)
    * Moderated the March 2020 Caucus for Women in Statistics Lunch & Learn on [Navigating social media and managing your professional presence online](https://cwstat.org/march-31st-lunch-learn-on-creating-a-professional-online-presence-view-recording/). Check out my [blog post](blog_cws_social_media_webinar.html) about this Lunch & Learn for more information. 

<br>

## [DataKind](https://www.datakind.org/) Volunteer
*  Review applications for Google.org’s [AI Impact Challenge](https://ai.google/social-good/impact-challenge) on the criteria of impact, feasibility, use of artificial intelligence (AI), scalability and responsibility to help identify the most promising ideas that aim to apply AI to achieve positive social impact. (February 2019)  
* Review applications for data.org's [Inclusive Growth and Recovery Challenge](https://www.data.org/challenge/) to identify the most promising proposals that use data science that spur economic growth and recovery (July 2020)
