---
title: "Current areas of focus"
# - text: "research"
#       href: projects.html
#     - text: "publications"
#       href: publications.html
#     - text: "presentations"
#       href: presentations.html
---
<link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="fonts/academicons.min.css"/>

###Women in STEM
* [Language and Tools for Establishing Influence as an Early-Career Statistician](https://ww2.amstat.org/meetings/wsds/2017/onlineprogram/AbstractDetails.cfm?AbstractID=303802) Women in Statistics and Data Science Conference, 2017  
    - [Corresponding AmStat News article](http://magazine.amstat.org/blog/2018/05/01/earlycareertools/)  
* [New York Academy of Sciences' 1000 girls, 1000 futures mentoring program](http://magazine.amstat.org/blog/2018/11/01/1000-girls-1000-futures/?utm_source=informz&utm_medium=email&utm_campaign=amstatnews&_zs=UvcOe1&_zl=vBfH5)  
*  Member of [RLadies NYC](http://www.rladiesnyc.org/).
<br>

###Hospital profiling
I am part of a team of statisticians, health services researchers and oncologists at MSK working to measure the quality of surgical cancer care provided to patients across the United States. Hospital profiling refers to measuring each hospitals' specific patient-level outcomes, and potentially reporting those outcomes publicly so that patients may make informed decisions regarding where to pursue care and hospitals may work towards improving their quality, when needed. This project is multifaceted, and involves validating a relevant data source for this endeavor, considering how to evaluate hospitals with few surgeries from which we can observe outcomes, and weighing the different statistical methods available to determine which is most appropriate given its implications.  

###Opioid use in older adults with cancer  
Cancer survivors may be at increased risk of opioid-related harms, because of exposure to opioids during treatment, high prevalence of pain after treatment, and heightened risk of addiction among people with tobacco- and alcohol-related cancers. Using the Surveillance, Epidemiology and End Results (SEER) registry linked to Medicare claims, we conducted a retrospective matched cohort study to compare receipt of chronic opioid therapy (90-days of continuous use) between cancer survivors and cancer-free controls from 2008 through 2014.  

###Quality of life in melanoma patients treated with immunotherapy  
Given the rapid pace of incorporation of checkpoint inhibitors into practice and the rising number of patients treated with these drugs as part of routine care, an assessment of the impact of these agents on patient quality of life, with attention to both the symptom and financial burdens associated with immunotherapy, is necessary to optimize care. 

###Hospital interpreter policies  
Patients with limited English proficiency (LEP) are at risk of impaired communication with their clinicians and thus disparities in cancer treatment completion. Despite knowledge that the use of professional interpreters improves patient care for LEP patients, research has shown that clinicians underuse language services in favor of their own, often limited, non-English skills. We conducted a nation-wide hospital survey to investigate the current policies of hospitals that care for LEP cancer patients to inform guidelines for linguistically appropriate care, which was identified as a priority by the Commission to End Health Disparities.
<br>

<!-- ###Professional development -->
<!-- Here are some tools I'm using to work towards my 2019 professional devlopment goals of increasing my R skills, incorporating Git into my workflow and using shiny apps.   -->

<!-- * R -->
<!--     + [Advanced R](http://adv-r.had.co.nz/) -->
<!-- ###Efficient workflows -->
<!-- * Git -->
<!--     + [Happy Git and GitHub for the useR](http://happygitwithr.com/) -->
<!--     + ["Git with Joyce," a tutorial on GitHub Workflows, Joyce Robbins](https://github.com/jtr13/codehelp/blob/master/GitHubWorkflow.pdf) -->
<!-- <br> -->
<!-- * Shiny -->
<!--     + Julia Wrobel's R Ladies [tutorial](http://juliawrobel.com/tutorials/shiny_tutorial_nba.html) with NBA Data for the R Ladies NYC meetup on May 8, 2018 -->
<!-- * Demo of my project management shiny application available on [GitHub](https://github.mskcc.org/laveryj/Project-Management-Shiny-App)   -->
<!-- <br><br> -->
